# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://lleely.github.io
title: 吕莉莉
email: 3242236512@qq.com
author: Lily
description: > # "Lleely's Portfolio"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: linkedin
    title: 作品展示
    url: https://www.yuque.com/docs/share/b92aa53e-f495-415f-b746-7c6afa36e04b?#
  #- icon: github
  #  title: 在线简历
  #  url: https://github.com/lleely
  - icon: file-pdf-o
    title: PDF简历
    url: https://lleely.github.io/rsc/resume.pdf
  - icon: envelope-o
    title: 联系邮箱
    url: mailto:3242236512@qq.com
