# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://lleely.github.io
title: 吕莉莉
email: 3242236512@qq.com
author: Lleely
description: > # "Lleely's Portfolio"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: linkedin
    title: 作品
    url: https://www.linkedin.com/in/kevinlinvxd
  - icon: github
    title: GitHub
    url: https://github.com/kevinlinvxd
  - icon: file-pdf-o
    title: 简历
    url: https://lleely.github.io/rsc/resume.pdf
  - icon: envelope-o
    title: 邮箱
    url: mailto:3242236512@qq.com
